name: web ci/cd

on:
  push:
    paths:
      - web
      - .github/workflows/web.yml
  pull_request:
    paths:
      - web
      - .github/workflows/web.yml

defaults:
  run:
    working-directory: web

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - run: npm ci
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'ref/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - run: npm i -g vercel
      - run: vercel --token ${{ secrets.VERCEL_ACCESS_TOKEN }} --confirm --name {{ secrets.VERCEL_PROJECT_NAME }} --prod